syntax = "proto3";
option java_multiple_files = true;
package com.example.grpc;

// The request message containing the game command.
message GameCommandRequest {
  string command = 1;
  string target = 2;
  int32 userId = 3;
}

// The response message containing the result of the command.
message GameCommandResponse {
  string message = 1;
}

message JoinLobbyRequest {
  int32 lobbyID = 1; // 0 = "Start Lobby", fünstelligezahl = "Join Lobby"
  string clientTyp = 2; // "player" oder "mob"
}

message JoinLobbyResponse {
  bool success = 1; // true wenn ok false wenn nicht
  int32 lobbyID = 2; // bei Join Lobby fünstelligezahl back
  int32 characterID = 3; // Eigene CharID
  int32 userID = 4; // UserID fürs joinen
}

// The Game service definition.
service GameService {
  // Sends a game command to the server and receives a response.
  rpc SendGameCommand(stream GameCommandRequest) returns (stream GameCommandResponse);
}

service ManageService {
  // Joins the game
  rpc JoinLobby(JoinLobbyRequest) returns (JoinLobbyResponse);
}
