plugins {
	id 'java'
	id 'com.google.protobuf' version '0.9.4'
	id 'com.github.johnrengelman.shadow' version '7.1.0'
}
shadowJar {
	archiveBaseName.set('player')
	archiveVersion.set('1')
	archiveClassifier.set('')
	manifest {
		attributes 'Main-Class': 'de.roguemaster.player.SimpleClient'
	}
}
repositories {
	maven { // The google mirror is less flaky than mavenCentral()
		url "https://maven-central.storage-download.googleapis.com/maven2/" }
	mavenCentral()
	mavenLocal()
}
def grpcVersion = '1.61.0' // CURRENT_GRPC_VERSION
def protobufVersion = '3.25.2'
def protocVersion = protobufVersion

dependencies {
	// gRPC
	implementation "io.grpc:grpc-protobuf:${grpcVersion}"
	implementation "io.grpc:grpc-services:${grpcVersion}"
	implementation "io.grpc:grpc-stub:${grpcVersion}"
	implementation 'io.grpc:grpc-api:${grpcVersion}'
	compileOnly "org.apache.tomcat:annotations-api:6.0.53"

	implementation "com.google.protobuf:protobuf-java-util:${protobufVersion}"

	runtimeOnly "io.grpc:grpc-okhttp:${grpcVersion}"

	implementation 'com.googlecode.lanterna:lanterna:3.1.1'

	// JSON
	implementation group: 'com.google.code.gson', name: 'gson', version: '2.10.1'
}

protobuf {
	protoc { artifact = "com.google.protobuf:protoc:${protocVersion}" }
	plugins {
		grpc { artifact = "io.grpc:protoc-gen-grpc-java:${grpcVersion}" }
	}
	generateProtoTasks {
		all()*.plugins { grpc {} }
	}

}

sourceSets {
	main {
		proto {
			srcDir 'src/main/resources/proto'
		}
		java {
			srcDirs 'build/generated/source/proto/main/grpc'
			srcDirs 'build/generated/source/proto/main/java'
		}
	}
}

group = 'de.roguemaster'
version = '0.0.2-SNAPSHOT'

java {
	sourceCompatibility = '17'
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}


tasks.named('test') {
	useJUnitPlatform()
}
