package de.rougemaster.dungeon;

import com.example.grpc.*;
import com.google.gson.reflect.TypeToken;
import de.rougemaster.dungeon.character.enemyCharacter.EnemyCharacter;
import de.rougemaster.dungeon.character.enemyCharacter.EnemyCharacterFactory;
import de.rougemaster.dungeon.character.playerCharacter.PlayableCharacter;
import de.rougemaster.dungeon.dungeon.Dungeon;
import de.rougemaster.dungeon.game.GameState;
import de.rougemaster.dungeon.lobby.JSONManager;
import de.rougemaster.dungeon.lobby.LobbyCharType;
import de.rougemaster.dungeon.lobby.LobbyFacade;
import de.rougemaster.dungeon.lobby.messageData.GameStateMessage;
import de.rougemaster.dungeon.lobby.messageData.JoinLobbyResponseMessage;
import de.rougemaster.dungeon.lobby.messageData.RoomMessage;
import io.grpc.Grpc;
import io.grpc.InsecureServerCredentials;
import io.grpc.Server;
import io.grpc.stub.StreamObserver;

import java.io.IOException;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

public class DungeonApplication {
    private static final Logger logger = Logger.getLogger(DungeonApplication.class.getName());
    private Server server;
    private LobbyFacade lobbyFacade;

    private void start() throws IOException {
        int port = 8811;
        lobbyFacade = LobbyFacade.getInstance();
        this.server = Grpc.newServerBuilderForPort(port, InsecureServerCredentials.create())
                .addService(new GameServiceImpl(lobbyFacade))
                .addService(new ManageServiceImpl(lobbyFacade))
                .build()
                .start();
        logger.info("Server started, listening on " + port);

        Runtime.getRuntime().addShutdownHook(new Thread() {
            public void run() {
                System.err.println("*** shutting down gRPC server since JVM is shutting down");

                try {
                    DungeonApplication.this.stop();
                } catch (InterruptedException var2) {
                    var2.printStackTrace(System.err);
                }

                System.err.println("*** server shut down");
            }
        });
    }

    private void stop() throws InterruptedException {
        if (this.server != null) {
            this.server.shutdown().awaitTermination(30L, TimeUnit.SECONDS);
        }
    }

    private void blockUntilShutdown() throws InterruptedException {
        if (this.server != null) {
            this.server.awaitTermination();
        }
    }

    public static void main(String[] args) throws IOException, InterruptedException {
        DungeonApplication server = new DungeonApplication();
        server.start();
        server.blockUntilShutdown();
    }

    /**
     * This class implements the GameService interface generated by gRPC
     */
    static class GameServiceImpl extends GameServiceGrpc.GameServiceImplBase {
        private final CopyOnWriteArrayList<StreamObserver<GameCommandResponse>> clients = new CopyOnWriteArrayList<>();
        private final ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);
        private LobbyFacade lobbyFacade;

        public GameServiceImpl(LobbyFacade lobbyFacade) {
            this.lobbyFacade = lobbyFacade;
            startGameStateUpdates(); // startet direkt beim erstellen des servers den loop zum updaten

        }

        @Override
        public StreamObserver<GameCommandRequest> sendGameCommand(StreamObserver<GameCommandResponse> responseObserver) {
            clients.add(responseObserver);
            System.out.println("Client connected, total clients: " + clients.size());

            return new StreamObserver<GameCommandRequest>() {
                @Override
                public void onNext(GameCommandRequest request) {
                    // Handle the incoming message from the client
                    // For example, update the game state based on the command
                    System.out.println("Received command: " + request.getCommand() + " " + request.getTarget());

                    // TODO: GameCommand nehmen und irgendeine Aktion ausführen SERVER SIDED
                }

                @Override
                public void onError(Throwable t) {
                    // Handle error
                    logger.info("Error Server sendGameCommand: " + t.getMessage());
                    clients.remove(responseObserver);
                }

                @Override
                public void onCompleted() {
                    // Complete the response stream
                    logger.info("Completed Server sendGameCommand, removing client");
                    clients.remove(responseObserver);
                    responseObserver.onCompleted();
                }
            };
        }

        private void startGameStateUpdates() {
            GameCommandResponse response = buildGameStateResponse();
            scheduler.scheduleAtFixedRate(() -> {
                try {
                    if (clients.isEmpty()) return; // No clients connected, nothing to do

                    for (StreamObserver<GameCommandResponse> client : clients) {

                        System.out.println("Sending game state update to client");
                        client.onNext(response); // Damit Rufen wir onNext von SimpleClient.java auf

                    }
                } catch (Exception e) {
                    logger.log(Level.SEVERE, "Exception in startGameStateUpdate", e);

                } catch (Throwable t) {
                    logger.log(Level.SEVERE, "Throwable caught in startGameStateUpdate", t);

                }
            }, 0, 6, TimeUnit.SECONDS);
        }

        private GameCommandResponse buildGameStateResponse() {
            // Build response based on game state
            Dungeon dungeon = new Dungeon(10, 2);

            PlayableCharacter p =new PlayableCharacter();
            p.teleport(dungeon.getRoomList().get(0));

            EnemyCharacter zombie = new EnemyCharacterFactory().createEnemy(EnemyCharacterFactory.EnemyTyp.Zombie);
            zombie.teleport(dungeon.getRoomList().get(0));

            GameState gameState = new GameState(
                    List.of(p)
                    , List.of(zombie)
                    , dungeon.getRoomList()
                    .stream()
                    .map(RoomMessage::new)
                    .toList());
            GameStateMessage gameStateMessage = new GameStateMessage(gameState);
            String message = new JSONManager<GameStateMessage>(new TypeToken<>() {
            }).write(gameStateMessage);
            return GameCommandResponse.newBuilder().setMessage(message).build();

        }

    }

    static class ManageServiceImpl extends ManageServiceGrpc.ManageServiceImplBase {
        private LobbyFacade lobbyFacade;
        private JoinLobbyResponseMessage lobbyResponseMessage;

        public ManageServiceImpl(LobbyFacade lobbyFacade) {
            this.lobbyFacade = lobbyFacade;
        }

        @Override
        public void joinLobby(JoinLobbyRequest request, StreamObserver<JoinLobbyResponse> responseObserver) {
            System.out.println("Received joinLobby request: " + request.getLobbyID());

            try {
                lobbyResponseMessage = lobbyFacade.joinLobby(request.getLobbyID(), LobbyCharType.PlayableCharacter);
            } catch (Throwable e) {
                e.printStackTrace();
            }

            // Bei Erfolg, success = true, lobbyID = LobbyID, characterID = CharacterID
            JoinLobbyResponse response = JoinLobbyResponse.newBuilder()
                    .setSuccess(lobbyResponseMessage.isSuccess())
                    .setLobbyID(lobbyResponseMessage.getLobbyId())
                    .setCharacterID(lobbyResponseMessage.getCharacterId())
                    .build();

            // Send the response back to the client
            responseObserver.onNext(response);
            responseObserver.onCompleted();
            System.out.println("Sent joinLobby response: " + response.getLobbyID() + " " + response.getSuccess() + " " + response.getCharacterID());
        }
    }
}
