package de.rougemaster.dungeon;

import com.example.grpc.*;
import com.google.gson.reflect.TypeToken;
import de.rougemaster.dungeon.character.enemyCharacter.EnemyCharacter;
import de.rougemaster.dungeon.character.enemyCharacter.EnemyCharacterFactory;
import de.rougemaster.dungeon.character.playerCharacter.PlayableCharacter;
import de.rougemaster.dungeon.dungeon.Dungeon;
import de.rougemaster.dungeon.game.GameState;
import de.rougemaster.dungeon.lobby.JSONManager;
import de.rougemaster.dungeon.lobby.LobbyCharType;
import de.rougemaster.dungeon.lobby.LobbyFacade;
import de.rougemaster.dungeon.lobby.LobbyMessage;
import de.rougemaster.dungeon.lobby.messageData.GameStateMessage;
import de.rougemaster.dungeon.lobby.messageData.JoinLobbyResponseMessage;
import de.rougemaster.dungeon.lobby.messageData.RoomMessage;
import io.grpc.Grpc;
import io.grpc.InsecureServerCredentials;
import io.grpc.Server;
import io.grpc.stub.StreamObserver;

import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

public class DungeonApplication {
    private static final Logger logger = Logger.getLogger(DungeonApplication.class.getName());
    private Server server;
    private LobbyFacade lobbyFacade;

    private void start() throws IOException {
        int port = 8811;
        lobbyFacade = LobbyFacade.getInstance();

        GameServiceImpl gameService = new GameServiceImpl(lobbyFacade);
        this.server = Grpc.newServerBuilderForPort(port, InsecureServerCredentials.create())
                .addService(gameService)
                .addService(new ManageServiceImpl(lobbyFacade))
                .build()
                .start();

        lobbyFacade.setServer(server);
        lobbyFacade.setGameService(gameService);
        logger.info("Server started, listening on " + port);

        Runtime.getRuntime().addShutdownHook(new Thread() {
            public void run() {
                System.err.println("*** shutting down gRPC server since JVM is shutting down");

                try {
                    DungeonApplication.this.stop();
                } catch (InterruptedException var2) {
                    var2.printStackTrace(System.err);
                }

                System.err.println("*** server shut down");
            }
        });
    }

    private void stop() throws InterruptedException {
        if (this.server != null) {
            this.server.shutdown().awaitTermination(30L, TimeUnit.SECONDS);
        }
    }

    private void blockUntilShutdown() throws InterruptedException {
        if (this.server != null) {
            this.server.awaitTermination();
        }
    }

    public static void main(String[] args) throws IOException, InterruptedException {
        DungeonApplication server = new DungeonApplication();
        server.start();
        server.blockUntilShutdown();
    }

    /**
     * This class implements the GameService interface generated by gRPC
     */
    public static class GameServiceImpl extends GameServiceGrpc.GameServiceImplBase {
        private final CopyOnWriteArrayList<StreamObserver<GameCommandResponse>> clients = new CopyOnWriteArrayList<>();
        private final Map<Integer,StreamObserver<GameCommandResponse>> clientToStreamConnection = new HashMap<>();
        private LobbyFacade lobbyFacade;


        public GameServiceImpl(LobbyFacade lobbyFacade) {
            this.lobbyFacade = lobbyFacade;
            this.lobbyFacade.setClientsToConnection(clientToStreamConnection);
        }

        @Override
        public StreamObserver<GameCommandRequest> sendGameCommand(StreamObserver<GameCommandResponse> responseObserver) {
            clients.add(responseObserver);
            System.out.println("Client connected, total clients: " + clients.size());

            return new StreamObserver<GameCommandRequest>() {
                private Integer userId = null;

                @Override
                public void onNext(GameCommandRequest request) {
                    System.out.println("Received command: " + request.getCommand() + " " + request.getTarget());


                    if(request.getCommand().equals("initialize") && lobbyFacade.isClientIdExisting(request.getUserId())){
                        userId = request.getUserId();
                        clientToStreamConnection.put(userId, responseObserver);
                    } else if(clientToStreamConnection.containsKey(request.getUserId())) {
                        lobbyFacade.setGameCommand(request.getUserId(), new LobbyMessage(request.getCommand(), request.getTarget()));
                    }

                }

                @Override
                public void onError(Throwable t) {
                    logger.log(Level.INFO, "Error in sendGameCommand: " + t.getMessage());
                    // Remove the client from the list and the map
                    if (userId != null) {
                        clientToStreamConnection.remove(userId);
                    }
                    clients.remove(responseObserver);
                }

                @Override
                public void onCompleted() {
                    logger.info("Completed Server sendGameCommand, removing client");
                    // Remove the client from the list and the map
                    if (userId != null) {
                        clientToStreamConnection.remove(userId);
                    }
                    clients.remove(responseObserver);
                    responseObserver.onCompleted();
                }
            };
        }

    }

    static class ManageServiceImpl extends ManageServiceGrpc.ManageServiceImplBase {
        private LobbyFacade lobbyFacade;
        private JoinLobbyResponseMessage lobbyResponseMessage;

        public ManageServiceImpl(LobbyFacade lobbyFacade) {
            this.lobbyFacade = lobbyFacade;
        }

        @Override
        public void joinLobby(JoinLobbyRequest request, StreamObserver<JoinLobbyResponse> responseObserver) {
            System.out.println("Received joinLobby request: " + request.getLobbyID());

            try {
                lobbyResponseMessage = lobbyFacade.joinLobby(request.getLobbyID(), LobbyCharType.PlayableCharacter);
            } catch (Throwable e) {
                e.printStackTrace();
            }

            // Bei Erfolg, success = true, lobbyID = LobbyID, characterID = CharacterID
            JoinLobbyResponse response = JoinLobbyResponse.newBuilder()
                    .setSuccess(lobbyResponseMessage.isSuccess())
                    .setLobbyID(lobbyResponseMessage.getLobbyId())
                    .setCharacterID(lobbyResponseMessage.getCharacterId()) // für jeden client seine lokalePlayerId
                    .setUserID(lobbyResponseMessage.getClientId())  // sende mit für befehle damit server weiß wer was macht
                    .build();

            // Send the response back to the client
            responseObserver.onNext(response);
            responseObserver.onCompleted();
            System.out.println("Sent joinLobby response: " + response.getLobbyID() + " " + response.getSuccess() + " " + response.getCharacterID() + " " + response.getUserID());
        }
    }
}
